### ISSUE TITLE
Preloads after the hook don't get appended

### ISSUE THREAD

**Issue by kobeaerts** [ryssbowh/craft-prefetch#2]
If I call `{% hook 'prefetch' %}` none of the `craft.prefetch...` calls after the hook get appended.

This would be handy if we work with a matrix block with a image carousel where we want to preload the async JavaScript code for this block :)

**Comment by ryssbowh** [comment]
That's the intended behaviour, the preloads/prefetch must be in the header so must be registered before the hook is called.

Several reasons why it may not work the way you want :
- the registration happens within a cache tag, in which case it won't executed once the cache exists
- the registration happens within a block tag. This one is not ideal but that's just the way twig works.

So either register before rendering using php, or register outside of block elements:

```
{% extends "html" %}

{% do craft.prefetch.preload('test.css') %}

{% block content %}
    <p>Content</p>
{% endblock %}
```

**Comment by kobeaerts** [comment]
Hmm I see, but wouldn't it be cool if we could reference preloads dynamicly based on the content (includes) of the page.

I would see it working like the Craft  `css` and `js` tags, you can use them anywhere and they will output it in the header.
Cfr: https://craftcms.com/docs/3.x/dev/tags.html#js

**Comment by ryssbowh** [comment]
Indeed,
I'll have a think, it may be possible to register within a block tag, using an event rather than a hook.
For registration within the cache tag, there's nothing I can do.

**Comment by ryssbowh** [comment]
Hi,
This is now working in 1.1.0. 
Note that the hook has been removed.
